services:
 
  postgres:
 
    image: postgres:15
 
    container_name: postgres_music
 
    environment:
 
      POSTGRES_USER: postgres
 
      POSTGRES_PASSWORD: postgres
 
      POSTGRES_DB: musicdb
 
    ports:
 
      - "54321:5432"
 
    volumes:
 
      - pgdata:/var/lib/postgresql/data
 
  springboot-app:
    image: aaguamaninga/backend-music:latest
    ports:
      - "9090:8080"
    container_name: backend-springboot-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/musicdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
  
  react-app:
    image: b1uefeet/frontend-music:latest
    ports:
      - "8080:80"
    container_name: frontend-react-container
    environment:
      REACT_APP_BASE_URL: http://localhost:9090/API/v1.0/demo
 
volumes:
 
  pgdata: